= FW4SPL becomes Sight !
:hp-tags: fw4spl, sight, release, 18.0.0

Hi folks,

Lots of things happened since the last post ! It has been a while since we wanted to change the name of our framework into something that makes more sense. We finally found it and we are now proud to announce that FW4SPL was renamed into **Sight**, for **S**urgical **I**mage **G**uidance and **H**ealthcare **T**oolkit ! We kept the version numbering though, so the first version  is **Sight 18.0**.

The blog URL has not changed yet, however we opened a new organization on https://github.com/IRCAD-IHU[GitHub] to host the new repositories. You said new repositories ? Yes ! The renaming is not only a cosmetic change. In our constant effort to make the software easier to use for developers, we merged all four open-source repositories into a single one ! So you longer need to clone multiple repositories, the new https://github.com/IRCAD-IHU[Sight] contains everything.

You may also have noticed that we replaced **framework** by **toolkit** in the title of our  software. This is to emphasize the fact that you can now use **Sight** as any library thanks to the new SDK mode. You can use any function from an non-Sight application, or even build your new bundle or application outside of the main **Sight** source tree.

Last and not least, we worked hard to provide binaries for the numerous dependencies of Sight thanks to https://conan.io/[Conan]. Currently, we support Linux Mint18, Windows 10 and MacOs. That means you will save hours of build time, which should really help people to evaluate Sight the first time, and make them more productive when they really use it. This is still an experimental feature though but we are stabilizing it for **Sight 18.1**. This already makes our life so much easier, that we plan to drop **sight-deps** for **Sight 19.0** and makes Conan packages the official way.

In you want the whole changelog, please refer to the repository files:

- https://github.com/IRCAD-IHU/sight/blob/master/CHANGELOG.md
- https://github.com/IRCAD-IHU/sight-deps/blob/master/CHANGELOG.md
